<!-- DO NOT EDIT THIS FILE -->

<script lang="ts">
	import EventsCalendar from "$lib/components/ui/blocks/home/events-calendar.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Calendar, MapPin, Users } from "lucide-svelte";
	import type { PageData } from './$types';

	interface Props {
		data: PageData;
	}

	let { data }: Props = $props();
</script>

<svelte:head>
	<title>Üritused - Sukeldumisklubi</title>
	<meta name="description" content="Tutvu meie sukeldumisürituste kalendriga. Leia enda jaoks sobivad kursused, safarid ja teised põnevad sukeldumisalased üritused." />
</svelte:head>

<!-- Hero Section -->
<section class="relative flex items-center justify-center overflow-hidden bg-white py-4 px-4 h-[500px] md:h-[600px]">
	<!-- Card Container -->
	<div class="relative w-full max-w-screen bg-black rounded-3xl overflow-hidden h-full">
		<!-- Background -->
		<div class="absolute inset-0 z-0">
			<img 
				src="/photos/sukeldumisklubi-photo-credit-manomi-tennakoon-2016.webp"
				alt="Sukeldumisklubi üritused"
				class="w-full h-full object-cover"
				loading="eager"
				decoding="async"
				draggable="false"
			/>
			<!-- Black overlay -->
			<div class="absolute inset-0 bg-black/50"></div>
		</div>

		<!-- Content Overlay -->
		<div class="absolute bottom-0 left-0 right-0 p-8 z-10">
			<div class="mx-auto max-w-7xl px-6">
				<div class="max-w-4xl">
					
					
					<h1 class="text-4xl md:text-6xl font-bold text-white mb-6 tracking-tight">
						Sukeldumisüritused
					</h1>
					
					<p class="text-xl md:text-2xl text-gray-200 mb-8 max-w-3xl leading-relaxed">
						Avasta meie mitmekesiseid sukeldumisüritusi - alates algajate kursustest kuni põnevate safarideni. Leia enda jaoks sobiv väljakutse!
					</p>
					
					
				</div>
			</div>
		</div>
	</div>
</section>

<EventsCalendar events={data.events} />